company_name = input()
company_address = input()
company_phone_number = input()
company_fax_number = input()
company_web_site = input()
company_manager_first_name = input()
company_manager_last_name = input()
company_manager_age = input()
company_manager_phone = input()

print(company_name)
print(f'Address: {company_address}')
print(f'Tel. {company_phone_number}')
print('Fax: ', company_fax_number if company_fax_number != '' else 'no fax' )
print(f'Web site: {company_web_site}')
print(f'Manager: {company_manager_first_name} {company_manager_last_name} (age: {company_manager_age}, tel. {company_phone_number})')